name: ffigen
version: 0.0.1
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/ffigen
description: Experimental generator for FFI bindings.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3
